// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CollegeWebApplication.Models;

public partial class collegeContext : DbContext
{
    public collegeContext()
    {
    }

    public collegeContext(DbContextOptions<collegeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GroupCollege> GroupColleges { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-ILIAM;Initial Catalog=college;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GroupCollege>(entity =>
        {
            entity.HasKey(e => e.IdGroup).HasName("PK__group_co__8BE8BA1BF16CD1F1");

            entity.ToTable("group_college");

            entity.Property(e => e.IdGroup).HasColumnName("id_group");
            entity.Property(e => e.IdTeahcer).HasColumnName("id_teahcer");
            entity.Property(e => e.NameGroup)
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("name_group");

            entity.HasOne(d => d.IdTeahcerNavigation).WithMany(p => p.GroupColleges)
                .HasForeignKey(d => d.IdTeahcer)
                .HasConstraintName("FK__group_col__id_te__267ABA7A");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.IdStudent).HasName("PK__student__2BE2EBB6A112579E");

            entity.ToTable("student");

            entity.Property(e => e.IdStudent).HasColumnName("id_student");
            entity.Property(e => e.IdGroup).HasColumnName("id_group");
            entity.Property(e => e.NameStudent)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("name_student");
            entity.Property(e => e.SurnameStudent)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("surname_student");
            entity.Property(e => e.YearOfStudy).HasColumnName("year_of_study");

            entity.HasOne(d => d.IdGroupNavigation).WithMany(p => p.Students)
                .HasForeignKey(d => d.IdGroup)
                .HasConstraintName("FK__student__id_grou__29572725");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.IdTeacher).HasName("PK__teacher__1278D8CCA530181E");

            entity.ToTable("teacher");

            entity.Property(e => e.IdTeacher).HasColumnName("id_teahcer");
            entity.Property(e => e.Degree)
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasColumnName("degree");
            entity.Property(e => e.NameTeahcer)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("name_teahcer");
            entity.Property(e => e.SurnameTeacher)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("surname_teacher");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}