// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CollegeWebApplication.Models;

public partial class GroupCollege
{
    public int IdGroup { get; set; }

    [Display(Name = "Name")]
    public string NameGroup { get; set; }
    public int? IdTeahcer { get; set; }
    [Display(Name = "Teacher")]
    public virtual Teacher IdTeahcerNavigation { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}